version: "3.8"

services:
  postgres:
    container_name: postgres
    image: "postgres:15"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIME_ZONE=${TIME_ZONE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/data/db

volumes:
  db:
    driver:
      local