version: "3.8"

services:
  postgres:
    container_name: postgres
    image: "postgres:15"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=food-delivery-db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672" #default port
      - "15672:15672" # management ui
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
volumes:
  db:
    driver:
      local
  rabbitmq:
    driver:
      local