spring:
  config:
    import:
      - file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#  datasource:
#    url: jdbc:postgresql://localhost:5432/food-delivery-db
#    username: food-delivery-user
#    password: password
  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: update
    open-in-view: true


